//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyDatabase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyDatabase.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating constraints took {0} seconds.
        /// </summary>
        internal static string ActivatingConstraintsTookSeconds {
            get {
                return ResourceManager.GetString("ActivatingConstraintsTookSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Proceeding beyond this point will modify data.{0}Start the data copy? (Y|N).
        /// </summary>
        internal static string BeyondThisPoint {
            get {
                return ResourceManager.GetString("BeyondThisPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to check the exceptions.sql file..
        /// </summary>
        internal static string CheckExceptionsSqlFile {
            get {
                return ResourceManager.GetString("CheckExceptionsSqlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Columns missing in source table: .
        /// </summary>
        internal static string ColumnsMissingSource {
            get {
                return ResourceManager.GetString("ColumnsMissingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Columns missing in target table: .
        /// </summary>
        internal static string ColumnsMissingTarget {
            get {
                return ResourceManager.GetString("ColumnsMissingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0}% so far....
        /// </summary>
        internal static string CopiedSoFar {
            get {
                return ResourceManager.GetString("CopiedSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in {0}: {1}.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye..
        /// </summary>
        internal static string GoodBye {
            get {
                return ResourceManager.GetString("GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data took {0} seconds..
        /// </summary>
        internal static string LoadingDataTookSeconds {
            get {
                return ResourceManager.GetString("LoadingDataTookSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a number..
        /// </summary>
        internal static string NeedNumber {
            get {
                return ResourceManager.GetString("NeedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs to be investigated..
        /// </summary>
        internal static string NeedsInvestigation {
            get {
                return ResourceManager.GetString("NeedsInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be investigated..
        /// </summary>
        internal static string NeedsInvestigationLog {
            get {
                return ResourceManager.GetString("NeedsInvestigationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need an &apos;Y&apos; or an &apos;N&apos;..
        /// </summary>
        internal static string NeedYN {
            get {
                return ResourceManager.GetString("NeedYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not empty..
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimising....
        /// </summary>
        internal static string Optimising {
            get {
                return ResourceManager.GetString("Optimising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resized data file..
        /// </summary>
        internal static string ResizedDataFile {
            get {
                return ResourceManager.GetString("ResizedDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resized log file..
        /// </summary>
        internal static string ResizedLogFile {
            get {
                return ResourceManager.GetString("ResizedLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrusted foreign key relationships..
        /// </summary>
        internal static string RetrustRelationships {
            get {
                return ResourceManager.GetString("RetrustRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target database recovery model set to SIMPLE..
        /// </summary>
        internal static string SIMPLE {
            get {
                return ResourceManager.GetString("SIMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Database:.
        /// </summary>
        internal static string SourceDatabase {
            get {
                return ResourceManager.GetString("SourceDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source database cannot be target database..
        /// </summary>
        internal static string SourceIsTarget {
            get {
                return ResourceManager.GetString("SourceIsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found {0} tables in {1}..
        /// </summary>
        internal static string TablesFound {
            get {
                return ResourceManager.GetString("TablesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Database:.
        /// </summary>
        internal static string TargetDatabase {
            get {
                return ResourceManager.GetString("TargetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That took {0} minutes..
        /// </summary>
        internal static string ThatTookMinutes {
            get {
                return ResourceManager.GetString("ThatTookMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will try to connect to {0} ....
        /// </summary>
        internal static string TryConnect {
            get {
                return ResourceManager.GetString("TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated table statistics..
        /// </summary>
        internal static string UpdatedTableStatistics {
            get {
                return ResourceManager.GetString("UpdatedTableStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}You will be copying{0} from {1}{0}   to {2}{0}Is this correct? (Y|N) .
        /// </summary>
        internal static string YouWillBeCopying {
            get {
                return ResourceManager.GetString("YouWillBeCopying", resourceCulture);
            }
        }
    }
}
